# nginx proxy address - http://172.17.0.1:3008

name: psitransfer
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  psitransfer:
    image: psitrax/psitransfer:latest
    pull_policy: always
    container_name: psitransfer-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - psitransfer
    ports:
      - "172.17.0.1:3008:3000"
    environment:
      TZ: ${TZ:-America/New_York}
      PSITRANSFER_ADMIN_PASS: ${APP_ADMIN_PASS:-changeme_admin_password}
      PSITRANSFER_UPLOAD_PASS: ${UPLOAD_PASS:-changeme_upload_password}
      PSITRANSFER_UPLOAD_DIR: /data
    volumes:
      - ./volumes/data/psitransfer:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  psitransfer:
    name: psitransfer
    external: false
